import type { Metadata } from 'next';
import './globals.scss';

export const metadata: Metadata = {
  title: 'Portkey refferal',
  description: 'Generated by create next app',
  viewport: {
    viewportFit: 'cover',
    width: 'device-width',
    initialScale: 1,
    userScalable: false,
    minimumScale: 1,
    maximumScale: 1,
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
